// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import TranscriptionController from "./transcription_controller"

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)


// Register the transcription controller
application.register("transcription", TranscriptionController)

console.log("✅ Controllers registered!")
